### ISSUE TITLE
Top Border 

### ISSUE THREAD

**Issue by Vipin-V** [Vipin-V/Code-Magazine#4]
Top border bar is not extended till the right end.

**Comment by bilalshaikh292** [comment]
heyy @Vipin-V I would like to contribute ?

**Comment by bilalshaikh292** [comment]
![top border](https://github.com/Vipin-V/Code-Magazine/assets/110531971/db11d338-ab24-44e9-9f0f-6e1a965185d3)

**Comment by bilalshaikh292** [comment]
even I have done it

**Comment by bilalshaikh292** [comment]
Let me know for the Pull Request?

**Comment by Vipin-V** [comment]
sure u can

**Comment by bilalshaikh292** [comment]
Heyy @Vipin-V i wanted to conform that you wanted only top blue border or full navbar to extend till right most end

**Comment by Vipin-V** [comment]
Only the top blue border

**Comment by bilalshaikh292** [comment]
Ok then nav bar  will not extend till right end

**Comment by bilalshaikh292** [comment]
I will raise the pull request very soon

**Comment by Vipin-V** [comment]
Okay

**Comment by bilalshaikh292** [comment]
PR done
